In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('/content/drive/MyDrive/upi_transactions_2024.csv')

In [4]:
df.head()

,transaction id,timestamp,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank,receiver_bank,device_type,network_type,fraud_flag,hour_of_day,day_of_week,is_weekend
0,TXN0000000001,2024-10-08 15:17:28,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis,SBI,Android,4G,0,15,Tuesday,0
1,TXN0000000002,2024-04-11 06:56:00,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI,Axis,iOS,4G,0,6,Thursday,0
2,TXN0000000003,2024-04-02 13:27:18,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank,PNB,Android,4G,0,13,Tuesday,0
3,TXN0000000004,2024-01-07 10:09:17,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI,PNB,Android,5G,0,10,Sunday,1
4,TXN0000000005,2024-01-23 19:04:23,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis,Yes Bank,iOS,WiFi,0,19,Tuesday,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction id      250000 non-null  object
 1   timestamp           250000 non-null  object
 2   transaction type    250000 non-null  object
 3   merchant_category   250000 non-null  object
 4   amount (INR)        250000 non-null  int64
 5   transaction_status  250000 non-null  object
 6   sender_age_group    250000 non-null  object
 7   receiver_age_group  250000 non-null  object
 8   sender_state        250000 non-null  object
 9   sender_bank         250000 non-null  object
 10  receiver_bank       250000 non-null  object
 11  device_type         250000 non-null  object
 12  network_type        250000 non-null  object
 13  fraud_flag          250000 non-null  int64
 14  hour_of_day         250000 non-null  int64
 15  day_of_week         250000 non-null  object
 16  is_weekend          250000 non-null  int64
dtypes: int64(4), object(13)
memory usage: 32.4+ MB

In [6]:
df.isnull().sum()

transaction id        0
timestamp             0
transaction type      0
merchant_category     0
amount (INR)          0
transaction_status    0
sender_age_group      0
receiver_age_group    0
sender_state          0
sender_bank           0
receiver_bank         0
device_type           0
network_type          0
fraud_flag            0
hour_of_day           0
day_of_week           0
is_weekend            0
dtype: int64

In [7]:
df = df.drop_duplicates()

In [8]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction id      250000 non-null  object
 1   timestamp           250000 non-null  object
 2   transaction type    250000 non-null  object
 3   merchant_category   250000 non-null  object
 4   amount (INR)        250000 non-null  int64
 5   transaction_status  250000 non-null  object
 6   sender_age_group    250000 non-null  object
 7   receiver_age_group  250000 non-null  object
 8   sender_state        250000 non-null  object
 9   sender_bank         250000 non-null  object
 10  receiver_bank       250000 non-null  object
 11  device_type         250000 non-null  object
 12  network_type        250000 non-null  object
 13  fraud_flag          250000 non-null  int64
 14  hour_of_day         250000 non-null  int64
 15  day_of_week         250000 non-null  object
 16  is_weekend          250000 non-null  int64
dtypes: int64(4), object(13)
memory usage: 32.4+ MB

        amount (INR)     fraud_flag    hour_of_day     is_weekend
count  250000.000000  250000.000000  250000.000000  250000.000000
mean     1311.756036       0.001920      14.681032       0.285348
std      1848.059224       0.043776       5.188304       0.451581
min        10.000000       0.000000       0.000000       0.000000
25%       288.000000       0.000000      11.000000       0.000000
50%       629.000000       0.000000      15.000000       0.000000
75%      1596.000000       0.000000      19.000000       1.000000
max     42099.000000       1.000000      23.000000       1.000000

In [9]:
df['amount'] = pd.to_numeric(df['amount (INR)'], errors='coerce')
df['fraud_flag'] = df['fraud_flag'].astype(int)
df['is_weekend'] = df['is_weekend'].astype(int)

In [10]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [11]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 18 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction_id      250000 non-null  object
 1   timestamp           250000 non-null  object
 2   transaction_type    250000 non-null  object
 3   merchant_category   250000 non-null  object
 4   amount_(inr)        250000 non-null  int64
 5   transaction_status  250000 non-null  object
 6   sender_age_group    250000 non-null  object
 7   receiver_age_group  250000 non-null  object
 8   sender_state        250000 non-null  object
 9   sender_bank         250000 non-null  object
 10  receiver_bank       250000 non-null  object
 11  device_type         250000 non-null  object
 12  network_type        250000 non-null  object
 13  fraud_flag          250000 non-null  int64
 14  hour_of_day         250000 non-null  int64
 15  day_of_week         250000 non-null  object
 16  is_weekend          250000 non-null  int64
 17  amount              250000 non-null  int64
dtypes: int64(5), object(13)
memory usage: 34.3+ MB

,amount_(inr),fraud_flag,hour_of_day,is_weekend,amount
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,1311.756036,0.001920,14.681032,0.285348,1311.756036
std,1848.059224,0.043776,5.188304,0.451581,1848.059224
min,10.000000,0.000000,0.000000,0.000000,10.000000
25%,288.000000,0.000000,11.000000,0.000000,288.000000
50%,629.000000,0.000000,15.000000,0.000000,629.000000
75%,1596.000000,0.000000,19.000000,1.000000,1596.000000
max,42099.000000,1.000000,23.000000,1.000000,42099.000000

In [12]:
df = df.dropna()

In [13]:
df = df.drop_duplicates()

In [14]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 18 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction_id      250000 non-null  object
 1   timestamp           250000 non-null  object
 2   transaction_type    250000 non-null  object
 3   merchant_category   250000 non-null  object
 4   amount_(inr)        250000 non-null  int64
 5   transaction_status  250000 non-null  object
 6   sender_age_group    250000 non-null  object
 7   receiver_age_group  250000 non-null  object
 8   sender_state        250000 non-null  object
 9   sender_bank         250000 non-null  object
 10  receiver_bank       250000 non-null  object
 11  device_type         250000 non-null  object
 12  network_type        250000 non-null  object
 13  fraud_flag          250000 non-null  int64
 14  hour_of_day         250000 non-null  int64
 15  day_of_week         250000 non-null  object
 16  is_weekend          250000 non-null  int64
 17  amount              250000 non-null  int64
dtypes: int64(5), object(13)
memory usage: 34.3+ MB

,amount_(inr),fraud_flag,hour_of_day,is_weekend,amount
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,1311.756036,0.001920,14.681032,0.285348,1311.756036
std,1848.059224,0.043776,5.188304,0.451581,1848.059224
min,10.000000,0.000000,0.000000,0.000000,10.000000
25%,288.000000,0.000000,11.000000,0.000000,288.000000
50%,629.000000,0.000000,15.000000,0.000000,629.000000
75%,1596.000000,0.000000,19.000000,1.000000,1596.000000
max,42099.000000,1.000000,23.000000,1.000000,42099.000000

In [16]:
df = df.rename(columns={
    'transaction_id': 'transaction_id',
    'amount_(inr)': 'amount'
})
df['timestamp'] = pd.to_datetime(df['timestamp'])

In [17]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 18 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction_id      250000 non-null  object
 1   timestamp           250000 non-null  datetime64[ns]
 2   transaction_type    250000 non-null  object
 3   merchant_category   250000 non-null  object
 4   amount              250000 non-null  int64
 5   transaction_status  250000 non-null  object
 6   sender_age_group    250000 non-null  object
 7   receiver_age_group  250000 non-null  object
 8   sender_state        250000 non-null  object
 9   sender_bank         250000 non-null  object
 10  receiver_bank       250000 non-null  object
 11  device_type         250000 non-null  object
 12  network_type        250000 non-null  object
 13  fraud_flag          250000 non-null  int64
 14  hour_of_day         250000 non-null  int64
 15  day_of_week         250000 non-null  object
 16  is_weekend          250000 non-null  int64
 17  amount              250000 non-null  int64
dtypes: datetime64[ns](1), int64(5), object(12)
memory usage: 34.3+ MB

,timestamp,amount,fraud_flag,hour_of_day,is_weekend,amount
count,250000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,2024-07-01 15:57:20.438195456,1311.756036,0.001920,14.681032,0.285348,1311.756036
min,2024-01-01 00:05:10,10.000000,0.000000,0.000000,0.000000,10.000000
25%,2024-04-01 15:12:57.249999872,288.000000,0.000000,11.000000,0.000000,288.000000
50%,2024-07-01 14:34:17,629.000000,0.000000,15.000000,0.000000,629.000000
75%,2024-09-30 18:13:45,1596.000000,0.000000,19.000000,1.000000,1596.000000
max,2024-12-30 23:55:40,42099.000000,1.000000,23.000000,1.000000,42099.000000
std,NaN,1848.059224,0.043776,5.188304,0.451581,1848.059224

In [18]:
df = df.loc[:, ~df.columns.duplicated()]

In [19]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction_id      250000 non-null  object
 1   timestamp           250000 non-null  datetime64[ns]
 2   transaction_type    250000 non-null  object
 3   merchant_category   250000 non-null  object
 4   amount              250000 non-null  int64
 5   transaction_status  250000 non-null  object
 6   sender_age_group    250000 non-null  object
 7   receiver_age_group  250000 non-null  object
 8   sender_state        250000 non-null  object
 9   sender_bank         250000 non-null  object
 10  receiver_bank       250000 non-null  object
 11  device_type         250000 non-null  object
 12  network_type        250000 non-null  object
 13  fraud_flag          250000 non-null  int64
 14  hour_of_day         250000 non-null  int64
 15  day_of_week         250000 non-null  object
 16  is_weekend          250000 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(12)
memory usage: 32.4+ MB

,timestamp,amount,fraud_flag,hour_of_day,is_weekend
count,250000,250000.000000,250000.000000,250000.000000,250000.000000
mean,2024-07-01 15:57:20.438195456,1311.756036,0.001920,14.681032,0.285348
min,2024-01-01 00:05:10,10.000000,0.000000,0.000000,0.000000
25%,2024-04-01 15:12:57.249999872,288.000000,0.000000,11.000000,0.000000
50%,2024-07-01 14:34:17,629.000000,0.000000,15.000000,0.000000
75%,2024-09-30 18:13:45,1596.000000,0.000000,19.000000,1.000000
max,2024-12-30 23:55:40,42099.000000,1.000000,23.000000,1.000000
std,NaN,1848.059224,0.043776,5.188304,0.451581

In [20]:
df.to_csv("cleaned_upi_transactions.csv", index=False)

In [21]:
from google.colab import files

files.download("cleaned_upi_transactions.csv")

In [22]:
df['amount'] = pd.to_numeric(df['amount'], errors='coerce')

In [23]:
df[df['amount'].isna()]

Empty DataFrame
Columns: [transaction_id, timestamp, transaction_type, merchant_category, amount, transaction_status, sender_age_group, receiver_age_group, sender_state, sender_bank, receiver_bank, device_type, network_type, fraud_flag, hour_of_day, day_of_week, is_weekend]
Index: []

In [24]:
df['amount'] = df['amount'].fillna(0)

In [25]:
df['amount'] = df['amount'].astype('float64')

In [26]:
df['amount'].describe()

count    250000.000000
mean       1311.756036
std        1848.059224
min          10.000000
25%         288.000000
50%         629.000000
75%        1596.000000
max       42099.000000
Name: amount, dtype: float64

In [27]:
df.to_csv("cleaned_upi_transactions.csv", index=False)

In [28]:
from google.colab import files
files.download("cleaned_upi_transactions.csv")